<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, useForm } from '@inertiajs/vue3';
const props = defineProps({ clients: Array, users: Array, preselectedClientId: Number });
const form = useForm({ client_id: props.preselectedClientId ?? null, assigned_to: null, title: '', type: 'task', priority: 'normal', status: 'pending', due_at: '', notes: '' });
function submit() { form.post(route('sales.activities.store')); }
</script>
<template>
    <Head title="Activitate noua" /><AuthenticatedLayout><template #header><h2 class="text-xl font-semibold leading-tight text-gray-800">Activitate noua</h2></template><div class="py-8"><div class="mx-auto max-w-2xl sm:px-6 lg:px-8"><form class="space-y-6 rounded-lg bg-white p-6 shadow-sm" @submit.prevent="submit"><div class="grid grid-cols-1 gap-6 sm:grid-cols-2"><div><label class="block text-sm font-medium text-slate-700">Client *</label><select v-model.number="form.client_id" class="mt-1 block w-full rounded-md border-slate-300"><option :value="null" disabled>Selecteaza client</option><option v-for="client in clients" :key="client.id" :value="client.id">{{ client.name }}</option></select></div><div><label class="block text-sm font-medium text-slate-700">Responsabil</label><select v-model="form.assigned_to" class="mt-1 block w-full rounded-md border-slate-300"><option :value="null">Neasignat</option><option v-for="user in users" :key="user.id" :value="user.id">{{ user.name }}</option></select></div><div class="sm:col-span-2"><label class="block text-sm font-medium text-slate-700">Titlu *</label><input v-model="form.title" class="mt-1 block w-full rounded-md border-slate-300" /></div><div><label class="block text-sm font-medium text-slate-700">Tip</label><select v-model="form.type" class="mt-1 block w-full rounded-md border-slate-300"><option value="call">Apel</option><option value="email">Email</option><option value="meeting">Intalnire</option><option value="visit">Vizita</option><option value="task">Sarcina</option><option value="note">Nota</option></select></div><div><label class="block text-sm font-medium text-slate-700">Prioritate</label><select v-model="form.priority" class="mt-1 block w-full rounded-md border-slate-300"><option value="low">Scazuta</option><option value="normal">Normala</option><option value="high">Ridicata</option></select></div><div><label class="block text-sm font-medium text-slate-700">Termen</label><input v-model="form.due_at" type="datetime-local" class="mt-1 block w-full rounded-md border-slate-300" /></div><div class="sm:col-span-2"><label class="block text-sm font-medium text-slate-700">Note</label><textarea v-model="form.notes" rows="4" class="mt-1 block w-full rounded-md border-slate-300" /></div></div><div class="flex justify-end"><button :disabled="form.processing" class="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Salveaza activitatea</button></div></form></div></div></AuthenticatedLayout>
</template>
