<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
import { computed } from 'vue';
const props = defineProps({ order: Object, suppliers: Array, equipment: Array });
const form = useForm({ supplier_id: props.order.supplier_id, ordered_at: props.order.ordered_at ?? '', supplier_invoice_number: props.order.supplier_invoice_number ?? '', notes: props.order.notes ?? '', document: null, items: props.order.items.map((item) => ({ equipment_id: item.equipment_id, quantity: Number(item.quantity), unit_cost: Number(item.unit_cost) })) });
const total = computed(() => form.items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unit_cost || 0), 0));
function submit() { form.put(route('technical.purchase-orders.update', props.order.id), { forceFormData: true }); }
function addItem() { form.items.push({ equipment_id: '', quantity: 1, unit_cost: 0 }); }
function updateCost(item) { const product = props.equipment.find((entry) => entry.id == item.equipment_id); if (product) item.unit_cost = Number(product.cost_price); }
</script>
<template>
    <Head title="Editeaza comanda" /><AuthenticatedLayout><template #header><h2 class="text-xl font-semibold text-gray-800">Editeaza comanda {{ order.order_number }}</h2></template><div class="py-8"><div class="mx-auto max-w-5xl sm:px-6 lg:px-8"><form class="space-y-5 rounded-lg bg-white p-6 shadow-sm" @submit.prevent="submit"><div class="grid gap-4 sm:grid-cols-2"><select v-model="form.supplier_id" class="rounded-md border-slate-300"><option v-for="supplier in suppliers" :key="supplier.id" :value="supplier.id">{{ supplier.name }}</option></select><input v-model="form.ordered_at" type="date" class="rounded-md border-slate-300" /><input v-model="form.supplier_invoice_number" placeholder="Numar factura furnizor" class="rounded-md border-slate-300" /><input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" @input="form.document = $event.target.files[0]" class="rounded-md border-slate-300" /></div><div v-for="(item, index) in form.items" :key="index" class="grid gap-3 sm:grid-cols-12"><select v-model="item.equipment_id" required class="rounded-md border-slate-300 sm:col-span-6" @change="updateCost(item)"><option value="">Alege material</option><option v-for="product in equipment" :key="product.id" :value="product.id">{{ product.name }}</option></select><input v-model.number="item.quantity" type="number" min="0.01" step="0.01" class="rounded-md border-slate-300 sm:col-span-2" /><input v-model.number="item.unit_cost" type="number" min="0" step="0.01" class="rounded-md border-slate-300 sm:col-span-3" /><button type="button" class="text-red-600" @click="form.items.splice(index, 1)">Sterge</button></div><button type="button" class="text-sm text-blue-600" @click="addItem">+ Adauga material</button><textarea v-model="form.notes" rows="3" class="w-full rounded-md border-slate-300" placeholder="Note"></textarea><div class="flex items-center justify-between border-t pt-4"><strong>Total: {{ total.toLocaleString('ro-RO', { minimumFractionDigits: 2 }) }} lei</strong><button :disabled="form.processing" class="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Salveaza</button></div></form></div></div></AuthenticatedLayout>
</template>
