<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, router } from '@inertiajs/vue3';
const props = defineProps({ order: Object });
function money(value) { return Number(value).toLocaleString('ro-RO', { minimumFractionDigits: 2 }); }
function cancel() { if (confirm('Anulezi aceasta comanda?')) router.patch(route('technical.purchase-orders.cancel', props.order.id)); }
function receive() { if (confirm('Receptionezi cantitatile ramase?')) router.patch(route('technical.purchase-orders.receive', props.order.id)); }
</script>
<template>
    <Head :title="order.order_number" /><AuthenticatedLayout>
        <template #header><div class="flex items-center justify-between"><h2 class="text-xl font-semibold text-gray-800">Comanda {{ order.order_number }}</h2><Link :href="route('technical.purchase-orders.index')" class="text-sm text-blue-600">Inapoi</Link></div></template>
        <div class="py-8"><div class="mx-auto max-w-4xl space-y-4 sm:px-6 lg:px-8"><div class="rounded-lg bg-white p-6 shadow-sm"><div class="grid gap-4 sm:grid-cols-3"><div><div class="text-xs text-slate-500">Furnizor</div><div class="font-medium">{{ order.supplier.name }}</div></div><div><div class="text-xs text-slate-500">Status</div><div class="font-medium">{{ order.status }}</div></div><div><div class="text-xs text-slate-500">Factura furnizor</div><div>{{ order.supplier_invoice_number || '-' }}</div></div></div><div v-if="order.notes" class="mt-4 text-sm text-slate-600">{{ order.notes }}</div><a v-if="order.document_url" :href="order.document_url" target="_blank" class="mt-3 inline-block text-sm text-blue-600">Deschide documentul furnizor</a></div><div class="overflow-x-auto rounded-lg bg-white shadow-sm"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50"><tr><th class="px-4 py-3 text-left text-xs uppercase text-slate-500">Material</th><th class="px-4 py-3 text-right text-xs uppercase text-slate-500">Cantitate</th><th class="px-4 py-3 text-right text-xs uppercase text-slate-500">Receptionat</th><th class="px-4 py-3 text-right text-xs uppercase text-slate-500">Cost</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="item in order.items" :key="item.id"><td class="px-4 py-3">{{ item.equipment.name }}</td><td class="px-4 py-3 text-right">{{ item.quantity }}</td><td class="px-4 py-3 text-right">{{ item.received_quantity }}</td><td class="px-4 py-3 text-right">{{ money(item.quantity * item.unit_cost) }} lei</td></tr></tbody></table></div><div class="flex justify-end gap-3"><Link v-if="order.status === 'draft'" :href="route('technical.purchase-orders.edit', order.id)" class="rounded-md border border-slate-300 px-4 py-2 text-sm">Editeaza</Link><button v-if="!['received','cancelled'].includes(order.status)" class="rounded-md bg-emerald-600 px-4 py-2 text-sm font-semibold text-white" @click="receive">Receptioneaza</button><button v-if="['draft','ordered','partially_received'].includes(order.status)" class="rounded-md bg-red-600 px-4 py-2 text-sm font-semibold text-white" @click="cancel">Anuleaza</button></div></div></div>
    </AuthenticatedLayout>
</template>
